CREATE TABLE IF NOT EXISTS file (
    id   BIGINT NOT NULL GENERATED ALWAYS AS IDENTITY,
    name VARCHAR NULL,
    uri  VARCHAR NOT NULL,
    uploaded  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT file_pk PRIMARY KEY (id)
);

ALTER TABLE "image" ADD COLUMN gallery bool NULL DEFAULT false;
ALTER TABLE "image" ADD COLUMN uploaded timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP;